// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson194f723eDecodeConcursHandlers(in *jlexer.Lexer, out *LikesT) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "likes":
			if in.IsNull() {
				in.Skip()
				out.Likes = nil
			} else {
				in.Delim('[')
				if out.Likes == nil {
					//fmt.Println("nil")
					if !in.IsDelim(']') {
						out.Likes = make([]LTemp, 0, 2)
					} else {
						out.Likes = []LTemp{}
					}
				} else {
					out.Likes = (out.Likes)[:0]
				}
				//fmt.Println(cap(out.Likes))
				for !in.IsDelim(']') {
					var v1 LTemp
					(v1).UnmarshalEasyJSON(in)
					out.Likes = append(out.Likes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
	//fmt.Println(cap(out.Likes))
}
func easyjson194f723eEncodeConcursHandlers(out *jwriter.Writer, in LikesT) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"likes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Likes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Likes {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LikesT) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson194f723eEncodeConcursHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LikesT) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson194f723eEncodeConcursHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LikesT) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson194f723eDecodeConcursHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LikesT) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson194f723eDecodeConcursHandlers(l, v)
}
func easyjson194f723eDecodeConcursHandlers1(in *jlexer.Lexer, out *LTemp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "liker":
			out.Liker = int64(in.Int64())
		case "likee":
			out.Likee = int64(in.Int64())
		case "ts":
			out.Ts = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson194f723eEncodeConcursHandlers1(out *jwriter.Writer, in LTemp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"liker\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Liker))
	}
	{
		const prefix string = ",\"likee\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Likee))
	}
	{
		const prefix string = ",\"ts\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Ts))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LTemp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson194f723eEncodeConcursHandlers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LTemp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson194f723eEncodeConcursHandlers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LTemp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson194f723eDecodeConcursHandlers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LTemp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson194f723eDecodeConcursHandlers1(l, v)
}
